import portalApi from "../../../PortalApi/portalApi";
import ProductDetails from "../../../product-details/ProductDetails";
import { extractItemCode } from "../../../utils/helper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "create next app",
};

export default async function Page(props) {
  const { product } = props.params;
  const itemCode = extractItemCode(product);
  const productDetails = await portalApi.getProductDetailsWithItemCode(
    itemCode
  );
  return (
    <menu>
      <ProductDetails data={productDetails.docs[0]} breadcrumb={props.params} />
    </menu>
  );
}
