import Header from "../components/header/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "create next app",
};
export default function Home() {
  return (
    <main>
      <Header />
      <h1>Welcome !</h1>
    </main>
  );
}
