export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "create next app",
};

// import "flowbite";
import portalApi from "./PortalApi/portalApi";
import HomePage from "./Home";

export default async function Home() {
  const data = await portalApi.getHomePageData();
  const homeBanner = await portalApi.getHomeBanners();
  return <HomePage data={data?.docs} homeBanner={homeBanner} />;
}
