export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "create next app",
};

import { SearchList } from "./SearchList";

export default function Home(props) {
  return <SearchList props={props} />;
}
