export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "create next app",
};
import { Filter } from "@/components/Filter";
import { ProductCard } from "@/components/ProductCard";
import Breadcrumb from "@/components/globals/BreadCrumb";
import "flowbite";

export default function Home() {
  return (
    <div className="p-2 pb-4 flex flex-col gap-6 w-full flex-grow bg-white">
      <Breadcrumb />
      <div className="flex w-full gap-4">
        <Filter />
        <div className="flex flex-col gap-4">
          <h1 className="text-2xl font-bold">Speakers</h1>
          <hr />
          <div className="grid grid-cols-3 lg:grid-cols-4 gap-5">
            {Array.from({ length: 12 }).map((_, index) => (
              <ProductCard key={index} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
