export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "create next app",
};

import ProductDetails from "../ProductDetails";

export default function Page(props) {
  return (
    <menu>
      <ProductDetails props={props} />
    </menu>
  );
}
